minimum_prek_version = "0.5.4"

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace", priority = 0 },
    { id = "end-of-file-fixer", priority = 1 },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "rustfmt"
name = "Format Rust"
entry = "bash tools/run-in-env cargo fmt --all"
language = "system"
files = '\.rs$'
pass_filenames = false
priority = 2

[[repos.hooks]]
id = "justfmt"
name = "Format justfile"
entry = "bash tools/run-in-env just --unstable --fmt"
language = "system"
files = '^justfile$'
pass_filenames = false
priority = 2

[[repos.hooks]]
id = "clippy"
name = "Analyze Rust with Clippy"
entry = "bash tools/run-in-env cargo clippy --locked --all-targets -- -D warnings"
language = "system"
files = '(\.rs$|(^|/)(Cargo\.(toml|lock)|rust-toolchain\.toml)$)'
pass_filenames = false
priority = 3
